// GENERATED from the Soroban contract enums (Heliobond/contracts: investment_vault
// VaultError, project_registry RegistryError). Codes are stable on-chain, so this
// table only ever grows. Each entry is [variant name, message key inside the
// "ContractErrors" i18n namespace]. Regenerate when the contract enums change.

export type ContractErrorEntry = readonly [name: string, messageKey: string]

export const VAULT_ERROR_CODES: Readonly<Record<number, ContractErrorEntry>> = {
  1: ['AmountNotPositive', 'vault_AmountNotPositive'],
  2: ['DepositExceedsMaximum', 'vault_DepositExceedsMaximum'],
  3: ['InsufficientDeployable', 'category_unavailable'],
  4: ['SharesNotPositive', 'vault_SharesNotPositive'],
  5: ['WithdrawalExceedsLimit', 'vault_WithdrawalExceedsLimit'],
  6: ['InsufficientLiquid', 'vault_InsufficientLiquid'],
  7: ['YieldAmountNotPositive', 'category_invalid'],
  8: ['NoSharesOutstanding', 'category_unavailable'],
  9: ['InsufficientLiquidYield', 'vault_InsufficientLiquidYield'],
  10: ['InsuranceAlreadyClaimed', 'vault_InsuranceAlreadyClaimed'],
  11: ['InsufficientInsurance', 'vault_InsufficientInsurance'],
  12: ['FeeExceedsMaximum', 'category_invalid'],
  13: ['TransferToVaultBlocked', 'vault_TransferToVaultBlocked'],
  14: ['FeeRecipientNotSet', 'category_unavailable'],
  15: ['QueueEntryMissing', 'category_unavailable'],
  16: ['ClaimAmountNotPositive', 'category_invalid'],
  17: ['BelowMinCreditQuality', 'vault_BelowMinCreditQuality'],
  18: ['BelowMinGreenImpact', 'vault_BelowMinGreenImpact'],
  19: ['ThresholdOutOfRange', 'category_invalid'],
  20: ['BridgeNotSet', 'category_unavailable'],
  21: ['WormholeCoreNotSet', 'category_unavailable'],
  22: ['EmitterNotTrusted', 'category_bridge'],
  23: ['VaaAlreadyConsumed', 'category_bridge'],
  24: ['InvalidMultiSigThreshold', 'category_admin'],
  25: ['TooManyMultiSigSigners', 'category_admin'],
  26: ['NotMultiSigSigner', 'category_admin'],
  27: ['DuplicateApproval', 'category_admin'],
  28: ['InsufficientApprovals', 'category_admin'],
  29: ['UnsupportedStateVersion', 'category_unavailable'],
  30: ['ProjectNotFound', 'vault_ProjectNotFound'],
  31: ['DepositBelowMinimum', 'vault_DepositBelowMinimum'],
  32: ['WithdrawBelowMinimum', 'vault_WithdrawBelowMinimum'],
  33: ['SlippageLimitExceeded', 'vault_SlippageLimitExceeded'],
  34: ['Paused', 'vault_Paused'],
  35: ['RegistryPaused', 'vault_RegistryPaused'],
  36: ['DepositLocked', 'vault_DepositLocked'],
  37: ['NotEmergencyAdmin', 'category_admin'],
  38: ['MaxSupplyExceeded', 'vault_MaxSupplyExceeded'],
  39: ['SelfFundingNotAllowed', 'vault_SelfFundingNotAllowed'],
  40: ['DuplicateProjectId', 'category_invalid'],
  41: ['EmptyBatchDeposit', 'category_invalid'],
  42: ['FundingRoundActive', 'vault_FundingRoundActive'],
  43: ['InvestmentCapExceeded', 'vault_InvestmentCapExceeded'],
  44: ['ExceedsMaxTransactionAmount', 'vault_ExceedsMaxTransactionAmount'],
  45: ['BridgeTokenMismatch', 'category_bridge'],
  46: ['BridgeWrongTargetChain', 'category_bridge'],
  47: ['EmptyBatchFunding', 'category_invalid'],
  48: ['BatchTooLarge', 'category_invalid'],
  49: ['FlashLoanFeeOutOfRange', 'category_invalid'],
  50: ['FlashLoanCallbackFailed', 'category_bridge'],
  51: ['CarbonOracleNotSet', 'category_unavailable'],
  52: ['CarbonPriceNotPositive', 'category_invalid'],
  53: ['NoCarbonCreditsToIssue', 'category_invalid'],
  54: ['InsufficientCarbonCredits', 'category_invalid'],
  55: ['NegativeMaxTransactionAmount', 'category_invalid'],
  56: ['ComplianceEventNotFound', 'category_unavailable'],
  57: ['NoSnapshotTaken', 'category_unavailable'],
  58: ['OwnerNotSet', 'category_admin'],
  59: ['SelfTransferNotAllowed', 'vault_SelfTransferNotAllowed'],
  60: ['ProjectAlreadySettled', 'vault_ProjectAlreadySettled'],
  61: ['ProjectNotMature', 'vault_ProjectNotMature'],
}

export const REGISTRY_ERROR_CODES: Readonly<Record<number, ContractErrorEntry>> = {
  1: ['NotWhitelisted', 'registry_NotWhitelisted'],
  2: ['UriTooShort', 'category_invalid'],
  3: ['UriTooLong', 'category_invalid'],
  4: ['MaturityDateInPast', 'category_invalid'],
  5: ['ProjectLimitReached', 'category_unavailable'],
  6: ['CounterIntegrityViolation', 'category_unavailable'],
  7: ['ProjectNotFound', 'registry_ProjectNotFound'],
  8: ['ScoresOutOfRange', 'category_invalid'],
  9: ['NotAuthorizedToCertify', 'category_admin'],
  10: ['VotingWeightNotPositive', 'category_governance'],
  11: ['AlreadyVoted', 'category_governance'],
  12: ['ProposalNotFound', 'category_governance'],
  13: ['VotingPeriodEnded', 'category_governance'],
  14: ['ProposalAlreadyExecuted', 'category_governance'],
  15: ['VotingPeriodTooShort', 'category_governance'],
  16: ['VotingStillOpen', 'category_governance'],
  17: ['CollateralNotPositive', 'category_invalid'],
  18: ['NotProjectOwner', 'category_admin'],
  19: ['NoCollateral', 'category_invalid'],
  20: ['ProjectNotMature', 'registry_ProjectNotMature'],
  21: ['ReputationOutOfRange', 'category_invalid'],
  22: ['NotAuthorizedReputation', 'category_admin'],
  23: ['CreditQualityOutOfRange', 'category_invalid'],
  24: ['InvalidMultiSigThreshold', 'category_admin'],
  25: ['TooManyMultiSigSigners', 'category_admin'],
  26: ['NotMultiSigSigner', 'category_admin'],
  27: ['DuplicateApproval', 'category_admin'],
  28: ['InsufficientApprovals', 'category_admin'],
  29: ['InvalidUriScheme', 'category_invalid'],
  30: ['ProjectHasInvestments', 'registry_ProjectHasInvestments'],
  31: ['ProjectArchived', 'registry_ProjectArchived'],
  32: ['UnsupportedStateVersion', 'category_unavailable'],
  33: ['UpdateTooFrequent', 'registry_UpdateTooFrequent'],
  34: ['ProjectNotArchived', 'category_invalid'],
  35: ['Paused', 'registry_Paused'],
  36: ['NotEmergencyAdmin', 'category_admin'],
  37: ['BatchTooLarge', 'category_invalid'],
  38: ['AlreadyCertified', 'category_invalid'],
  39: ['ProposalDescriptionTooLong', 'category_governance'],
  40: ['EmptyBatchUpdate', 'category_invalid'],
  41: ['InvalidStatusTransition', 'category_invalid'],
  42: ['ProjectStatusUnchanged', 'category_invalid'],
  43: ['CompactStorageTooLarge', 'category_invalid'],
  44: ['VotingPeriodTooLong', 'category_governance'],
  45: ['VaultNotConfigured', 'category_unavailable'],
}
