#!/usr/bin/env bash
# Prepare a local Stellar network for the on-chain e2e journey (#607).
#
# Expects stellar/quickstart running in local mode with RPC and Horizon, e.g.
#   docker run -d --rm -p 8000:8000 --name stellar stellar/quickstart:latest \
#     --local --enable core,rpc,horizon
# and the `stellar` CLI on PATH. Then:
#   1. builds (or reuses) the Heliobond/contracts WASM,
#   2. creates admin / USDC issuer / investor accounts via friendbot,
#   3. issues a USDC asset, deploys its SAC and funds the investor and admin,
#   4. deploys ProjectRegistry and InvestmentVault,
#   5. writes the app + test environment to $OUT_ENV.
#
# Env overrides: RPC_URL, HORIZON_URL, FRIENDBOT_URL, CONTRACTS_DIR, CONTRACTS_REF,
# CONTRACTS_WASM_DIR (skip the build and use prebuilt *.wasm), OUT_ENV.
set -euo pipefail

RPC_URL="${RPC_URL:-http://localhost:8000/rpc}"
HORIZON_URL="${HORIZON_URL:-http://localhost:8000}"
FRIENDBOT_URL="${FRIENDBOT_URL:-http://localhost:8000/friendbot}"
PASSPHRASE="Standalone Network ; February 2017"
NETWORK=e2e-local
CONTRACTS_DIR="${CONTRACTS_DIR:-.e2e/contracts}"
CONTRACTS_REF="${CONTRACTS_REF:-main}"
OUT_ENV="${OUT_ENV:-e2e/chain/.env.chain.local}"

# 1 000 USDC for the investor, 100 USDC for the admin's yield payments (stroops).
INVESTOR_USDC=10000000000
ADMIN_USDC=1000000000

log() { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }

log "Waiting for Soroban RPC at $RPC_URL"
for _ in $(seq 1 90); do
  if curl -sf -X POST "$RPC_URL" -H 'Content-Type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"getHealth"}' | grep -q '"healthy"'; then
    break
  fi
  sleep 2
done
curl -sf -X POST "$RPC_URL" -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"getHealth"}' | grep -q '"healthy"' \
  || { echo "RPC never became healthy" >&2; exit 1; }

stellar network add "$NETWORK" --rpc-url "$RPC_URL" --network-passphrase "$PASSPHRASE"

if [ -n "${CONTRACTS_WASM_DIR:-}" ]; then
  WASM_DIR="$CONTRACTS_WASM_DIR"
else
  log "Building Heliobond/contracts@$CONTRACTS_REF"
  if [ ! -d "$CONTRACTS_DIR/.git" ]; then
    git clone --depth 1 --branch "$CONTRACTS_REF" https://github.com/Heliobond/contracts "$CONTRACTS_DIR"
  fi
  (cd "$CONTRACTS_DIR" && stellar contract build)
  WASM_DIR="$CONTRACTS_DIR/target/wasm32v1-none/release"
fi
for wasm in project_registry investment_vault; do
  [ -f "$WASM_DIR/$wasm.wasm" ] || { echo "missing $WASM_DIR/$wasm.wasm" >&2; exit 1; }
done

log "Creating and funding accounts"
for id in e2e-admin e2e-issuer e2e-investor; do
  stellar keys generate "$id" --overwrite >/dev/null
  curl -sf "$FRIENDBOT_URL?addr=$(stellar keys address "$id")" >/dev/null
done
ADMIN=$(stellar keys address e2e-admin)
ISSUER=$(stellar keys address e2e-issuer)
INVESTOR=$(stellar keys address e2e-investor)
USDC="USDC:$ISSUER"

log "Issuing $USDC and deploying its SAC"
USDC_SAC=$(stellar contract asset deploy --asset "$USDC" --source e2e-issuer --network "$NETWORK")
for id in e2e-investor e2e-admin; do
  stellar tx new change-trust --source "$id" --line "$USDC" --network "$NETWORK" >/dev/null
done
stellar tx new payment --source e2e-issuer --destination "$INVESTOR" --asset "$USDC" \
  --amount "$INVESTOR_USDC" --network "$NETWORK" >/dev/null
stellar tx new payment --source e2e-issuer --destination "$ADMIN" --asset "$USDC" \
  --amount "$ADMIN_USDC" --network "$NETWORK" >/dev/null

log "Deploying ProjectRegistry and InvestmentVault"
REGISTRY_ID=$(stellar contract deploy --wasm "$WASM_DIR/project_registry.wasm" \
  --source e2e-admin --network "$NETWORK" -- --admin "$ADMIN" --whitelister "$ADMIN")
VAULT_ID=$(stellar contract deploy --wasm "$WASM_DIR/investment_vault.wasm" \
  --source e2e-admin --network "$NETWORK" -- \
  --admin "$ADMIN" --usdc_sac "$USDC_SAC" --registry "$REGISTRY_ID")

mkdir -p "$(dirname "$OUT_ENV")"
cat >"$OUT_ENV" <<ENV
# Generated by scripts/e2e/setup-local-network.sh — local throwaway keys only.
NEXT_PUBLIC_STELLAR_NETWORK=testnet
NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE=$PASSPHRASE
NEXT_PUBLIC_SOROBAN_RPC_URL=$RPC_URL
NEXT_PUBLIC_HORIZON_URL=$HORIZON_URL
NEXT_PUBLIC_VAULT_CONTRACT_ID=$VAULT_ID
NEXT_PUBLIC_REGISTRY_CONTRACT_ID=$REGISTRY_ID
NEXT_PUBLIC_E2E_TEST_WALLET=true
E2E_NETWORK=$NETWORK
E2E_USDC_SAC=$USDC_SAC
E2E_REGISTRY_ID=$REGISTRY_ID
E2E_ADMIN_ALIAS=e2e-admin
E2E_ADMIN_ADDRESS=$ADMIN
E2E_INVESTOR_ADDRESS=$INVESTOR
E2E_INVESTOR_SECRET=$(stellar keys secret e2e-investor)
ENV

log "Local network ready — vault $VAULT_ID, USDC SAC $USDC_SAC"
echo "Environment written to $OUT_ENV"
